pipeline {
    agent any

    tools {
        maven 'MAVEN'
    }

    environment {
        NAMESPACE = 'devops'
    }

    stages {

        stage('Checkout') {
            steps {
                echo '📥 Checkout source code'
                checkout scm
            }
        }

        stage('Build with Maven') {
            steps {
                echo '🔨 Maven build'
                dir('student-management') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                echo '🔍 SonarQube analysis'
                dir('student-management') {
                    withSonarQubeEnv('Sonarqube') {
                        sh 'mvn sonar:sonar || true'
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo '🐳 Build Docker image'
                dir('student-management') {
                    sh 'docker build -t student-management-app:1.0 .'
                }
            }
        }
stage('KUBERNETES DEPLOY') {
    steps {
        echo '☸️ Deploy to Kubernetes'
        sh '''
            ls -l
            ls -l student-management
            ls -l student-management/k8s

            kubectl apply -f student-management/k8s
            kubectl get pods -n devops
            kubectl get svc -n devops
        '''
    }
}

stage('CREATE DEPARTMENT') {
    steps {
        script {
            echo "===== Creating Department via REST API ====="
            
            // Récupère le NodePort du service spring-service
            NODEPORT = sh(
                script: "kubectl get svc spring-service -n devops -o jsonpath='{.spec.ports[0].nodePort}'",
                returnStdout: true
            ).trim()
            
            echo "NodePort detected: ${NODEPORT}"
            
            // Appel du endpoint
            sh """
                sleep 10
                curl -X POST http://192.168.49.2:${NODEPORT}/student/department/createDepartment \\
                     -H "Content-Type: application/json" \\
                     -d '{"name": "Finance", "location": "Sfax"}'
            """
        }
    }
}

  
}
    }

    post {
        success {
            echo '✅ PIPELINE TERMINÉ AVEC SUCCÈS 🎉'
        }
        failure {
            echo '❌ PIPELINE ÉCHOUÉ'
        }
    }

